apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  creationTimestamp: null
  name: helloservice-primary
spec:
  host: helloservice-primary.podtatohead-production.svc.cluster.local
